services:
  backend:
    build: ./backend
    ports:
      - "4001:4000"
    restart: always
    environment:
      - PORT=4000
      - DB_HOST=investigacion-postgresinvestigacion-dgx6jl
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Seguridad2028@
      - DB_NAME=postgres
      - JWT_SECRET=cpo-investigaciones-secret-2026

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    restart: always
    depends_on:
      - backend
